#!/bin/bash
LOGFILE=/home/pi/timed/timed.log
WGETS="https://blog.adafruit.com/ https://www.iar.com/"
TMPDIR=/tmp/timedwget.tmp
echo "==" $(date) : "$0 $* ==" >> $LOGFILE 2>&1
mkdir -p $TMPDIR
rm -f $TMPDIR/*
cd $TMPDIR
for url in $WGETS; 
do  
  adr=$(echo $url | awk -- '{ print gensub("https://","","G") }' | awk -- '{ print gensub("http://","","G") }' | awk -- '{ print gensub("/[^ 	]*","","G") }' )
  (ping -c 1 $adr) |& grep -e 'transmitted'  >> $LOGFILE 2>&1 
  (time (wget -nv $url)) |& grep -v -e '^user' -e '^sys' -e '^$' >> $LOGFILE 2>&1
done;
echo "++" $(date) : "$0 $* ++" >> $LOGFILE 2>&1

