#!/bin/bash
LOGFILE=/home/boe/timed/wgetimed.log
WGETS="https://blog.adafruit.com/ https://www.iar.com/"
cd /tmp
echo "==" $(date) : "$0 $* ==" >> $LOGFILE 2>&1
for url in $WGETS; 
do  
  echo "$url" >> $LOGFILE 2>&1
  wget --delete-after --page-requisites --report-speed=bits $url |& tail -3 >> $LOGFILE 2>&1
done;

